name: Docker
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run CI
        run: |
            docker build . --file dockerfile -t mahaelkomey/iti-43-django:v1.0
            docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker push mahaelkomey/iti-43-django:v1.0
            docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker run -d -p 8000:8000 mahaelkomey/iti-43-django:v1.0
        
        
      
